feature: split eth-listener into two separate processes and use amqp …
repux/repux-metaindexer pull request #39
Opened 2018-08-16 10:41 UTC by przemczan

…queue to process events

2018-08-17 07:28 UTC, davo22 approved these changes

2018-08-29 08:04 UTC, przemeko requested changes

2018-08-29 08:04 UTC, przemeko commented on src/eth-event-consumer.ts
> +    const wsServer = new SocketIoServer(
Socket server started in the consumer?  Quite unusual :)

2018-08-29 08:21 UTC, kduralek approved these changes

2018-08-29 08:21 UTC, przemeko approved these changes

2018-08-29 08:22 UTC, przemeko requested changes

2018-08-29 08:22 UTC, przemeko commented on config/config.js
> +        url: 'amqp://repux-rabbitmq',
Use env please

2018-08-30 09:46 UTC, przemeko approved these changes
We will separate the consumer from WebSocket in next step.

2018-08-30 09:46 UTC, merged